powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Alpha' | Out-File -encoding ASCII fn_alphaRallypoint.sqf"
powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Bravo' | Out-File -encoding ASCII fn_bravoRallypoint.sqf"
powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Charlie' | Out-File -encoding ASCII fn_charlieRallypoint.sqf"
powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Delta' | Out-File -encoding ASCII fn_deltaRallypoint.sqf"
powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Echo' | Out-File -encoding ASCII fn_echoRallypoint.sqf"
powershell -Command "(gc fn_cmdRallypoint.sqf) -replace 'Cmd', 'Foxtrot' | Out-File -encoding ASCII fn_foxtrotRallypoint.sqf"